### ISSUE TITLE
A issue when simulate data  TypeError: 'Mutation' object does not support indexing

### ISSUE THREAD

**Issue by liveliiy** [stsmall/popsizeabc#1]
Hi, here is my command and error, and I'll very appreciate for your help or any good advice.

python2.7 simdata.py -o test1 -c popsizeabc.cfg 

Population size changes at the following times (in generations): [  0.00000000e+00   2.14369627e+01   7.04465278e+01   1.82493066e+02
   4.38655852e+02   1.02429976e+03   2.36320928e+03   5.42424800e+03
   1.24224491e+04   2.84218608e+04   6.50000000e+04]
Average LD will be computed for the following distance bins (in bp): [[1033918.0569903963, 1142751.5366735959], [375583.74537804374, 415118.8764704694], [152942.3898347558, 169041.58876473008], [64937.034934710871, 71772.512296259389], [28044.20555663187, 30996.227194172065], [12199.103833643367, 13483.220026658459], [5323.1138190533029, 5883.4415894799668], [2325.9053769652137, 2570.7375219089208], [1016.892611629097, 1123.9339391690021], [467.62030067201056, 516.84349021643266]]
Total number of statistics:31

Started the simualtions
Simulating replicate, 1
Traceback (most recent call last):
  File "simdata.py", line 223, in <module>
    Nmax, outfile_name, nb_seg, L, times, mac, mac_ld, wrdir, save_msp)
  File "simdata.py", line 171, in simdata
    interval_list, mac=mac, mac_ld=mac_ld, save_msp=save_msp)
  File "/panfs/sugon/home/xull/PopSizeABC_github/popsizeabc-master/popgen_abc.py", line 46, in simul_stats_one_rep_macld
    pos.append(mut[0])
TypeError: 'Mutation' object does not support indexing

Thank you very much

**Comment by stsmall** [comment]
Hi @liveliiy,
Hmm, I would recommend using the original version of popSizeABC. If there is a specific reason that you would like to use my fork, then I will need a few days to remember what everything does and check the code error. 
My initial guess is that the msprime has gone through some major updates and it may have changed the way the tree objects are accessed. It shouldnt be too difficult to fix this. Do you think you can send me your cfg file? stsmall@gmail.com.
thanks,
@stsmall
